### ISSUE TITLE
Amount of "conversations" in Dashboard limited?

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#100]
It seems that the amount of conversations in the Dashboard is limited. At least I can see only 8 conversations in the Dashboard of one of my accounts, but with NCC I see a lot more addresses that account had transactions with.

Can you clarify what happens here?

This is from https://github.com/NewEconomyMovement/NEMAndroidApp/issues/99

**Comment by LyubomirDominik** [comment]
We  take only 25 last transactions, so max number of conversations is 25

**Comment by jabo38** [comment]
Is that an artificial limit or is it limited by tech somehow?  25 is actually quite low.  I could have 25 messages with just one person and now the rest of the content with all my other contacts is gone.

**Comment by LyubomirDominik** [comment]
Look if you are in dashboard and scroll to bottom we can not upload new conversation as for this we need to download N transactions to see first entry of new account for conversation.
So if we have such history : 25 transactions to account1, 50 transactions to account2, 25 transactions to account3 - You will have 1 conversation (with account1) in app as we download 25 last transactions and if we need next conversation we need need to download next transactions by 25 up to that time when will be first transactions to new account.
So : 
   1 downloading = 1 conversation
   2 downloading = 2 conversation
   3 downloading = 2 conversation
   4 downloading = 3 conversation

And if we have history : 25 transactions to account1, 1024 transactions to account2, 25 transactions to account3

Result :
   1 downloading = 1 conversation
   2 - 40 downloading = 2 conversation
   41 downloading = 3 conversation (3rd conversation will contain only 1 transaction)
   42 downloading = 3 conversation (3rd conversation will contain 25 transactions)

The same situation is with scrolling inside the conversation.
If your API provide us with fetching transactions with predicates (filters), it would be real to do such functionality. For now we can not recommend you such functionality, as it could cause a range of issues.

**Comment by LyubomirDominik** [comment]
The problem with current api is that we can load [only 25 last transactions](http://bob.nem.ninja/docs/#requesting-transaction-data-for-an-account) and after loading finished, load another 25, and then another 25, etc.
And there is no guarantee that in the next data block there will be updates to current view (There can be next 25 transactions for existing item on dashboard, or 25 for another account on conversation). Also transaction data is relatively heavy, this is excessive load on both servers and devices. as we need to transfer unknown amount of data and process it.

**Comment by am4n0w4r** [comment]
The problem with current api is that we can load [only 25 last transactions](http://bob.nem.ninja/docs/#requesting-transaction-data-for-an-account) and after loading finished, load another 25, and then another 25, etc. And this has to be done one by one, not in parallel because of api limitations.
And there is no guarantee that in the next data block there will be updates to current view (There can be next 25 transactions for existing item on dashboard, or 25 for another account on conversation). Also transaction data is relatively heavy, this is excessive load on both servers and devices. as we need to transfer unknown amount of data and process it.
It would be nice if the api could allow getting last account transactions filtered by companion account (ideal for messages), and the last e.g. 25 transactions from/to unique companions, which is ideal for dashboard. It would be much more simple and efficient.

**Comment by jabo38** [comment]
@am4n0w4r I am passing this message on to devs.

**Comment by jabo38** [comment]
Ok, we talked about it.  we are aware that there is no guarantee, but we think it is still better to have 50 than 25 as long as we don't have the perfect solution with the improved API calls.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 23

**Comment by jabo38** [comment]
fixed
