### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#114]
I have been testing but iphone 6 with latest OS and latest NEM app gives me no notifications.

**Comment by kmiliak** [comment]
We've faced the same problem on our other IOS app, and we've checked everything carefully. 
Our suggestion is that it could be Apple issue. I've found post in Apple support about people complaining that neither push notifications or badge are not working. here is a link https://discussions.apple.com/thread/7229812?tstart=0

Of course we will also continue to research this problem.

**Comment by LyubomirDominik** [comment]
You check everything? 
If you don't have primary server you will not have notifications.
If you set update interval to "Never" you will also don't have notifications.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 20

Reason is in localization file structure change : 

You changed this: 
      "NOTIFICATION_MESSAGE" = "Account %@ have %d new transaction(s)";
To : 
       "NOTIFICATION_MESSAGE" = "%d new transaction(s) for account %@";

In first variant first argument accepts string  (%@ - String) and then (%d - Number)
In second variant first argument that accepts string  (%d - Number) and then (%@ - String)

After you changed first variant to second String accepts STRING instead of NUMBER and NUMBER instead of STRING. Please, mention that you can not change position of marks.  Sorry that haven't warned you earlier.

**Comment by jabo38** [comment]
okay, I might have changed some other orders and broken a couple of other things, so we need to check that.  thanks for looking into it.

**Comment by jabo38** [comment]
fixed but some how notifications are not finding a server sometime
