### ISSUE TITLE
0 XEM sent should be in grey not red

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#123]
![image](https://cloud.githubusercontent.com/assets/10395907/12954837/981c5d3c-d063-11e5-8e74-7fec98961a10.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 20

**Comment by jabo38** [comment]
fixed

**Comment by fyahfox** [comment]
while we had a bug on android with this, we talked about it again, and we came to the conclusion that it should just follow the same logic as all transactions do:
inbound is green and outbound is red.

there is really no advantage of having it in gray, because the fact that it is 0 XEM is visible anyways, but the red or green color gives you additional information (inbound or outbound).

so, sorry for the back and forth...

**Comment by kmiliak** [comment]
We are going to change this to previous version, but please in the future let's define everything o the discussion stage)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 25

**Comment by jabo38** [comment]
Fixed.
