### ISSUE TITLE
Request: possibility to copy text or wallet address in Messages menu.

### ISSUE THREAD

**Issue by boestin** [NewEconomyMovement/NEMiOSApp#25]
Sometimes I want to copy an address from the messages menu

**Comment by jabo38** [comment]
This is pretty much needed and I didn't realize it until playing with app and found out there was a big problem in the user experience. 

If I scan somebody's QR, I get their name in my address book.  But if I send somebody my QR and they send to me, I get their address only.  So every time I get a transaction from somebody, I don't really know who it is from because it is just an account number and the problem is there is no way to copy that address or add it to the address book with out getting out a piece of paper, writing it down manually and then going back to address book in the phone and then typing it in to the app by hand.  That simple can't happen for a user of an app.  

I am suggesting this then as an improvement.   It isn't a copy the address feature, but it serves the same purpose I think.  

![add contact](https://cloud.githubusercontent.com/assets/10395907/10867616/db15b5a2-80ae-11e5-92dc-ab2509a1f21c.png)

That is basically an add contact button next to their address, pressing on that auto-loads the address in the address book the same way a QR scan would have done.

**Comment by LyubomirDominik** [comment]
It must be agreed with project manager Khrystyna Miliak.

**Comment by kmiliak** [comment]
Please see here my last message https://trello.com/c/CSUEbxxL/7-questions

**Comment by fyahfox** [comment]
so, whats the stand?

**Comment by jabo38** [comment]
fixed
