### ISSUE TITLE
Create QR menu option does not work in Account Profile: I think the item can be removed.

### ISSUE THREAD

**Issue by boestin** [NewEconomyMovement/NEMiOSApp#26]
Tapping on the last menu item in Account Profile " Export Account"  Create QR gives no response.  
I think the option can be removed, since in User Info > My Info there is also a QR visible which probably is the same thing..

**Comment by jabo38** [comment]
The "Export Account" feature is suppose to put your private key in an encrypted QR so you can then export to a different phone.   In the future we can enable NCC or a webwallet produce these QRs too so that an account created on a computer can be safely imported into a phone directly without passing over the internet.  

The option in My Info is actually just a QR to share your name and account address.  

But yes, anyway, the option of "Export Account" should be deleted from my profile and get its own stand alone section in the More menu.  That should get some more info on it later in relation to exporting the private key so it is clear we are exporting a key and not an address so people won't be confused about this Export Account feature and the My Info feature in the future.

**Comment by LyubomirDominik** [comment]
It must be agreed with project manager Khrystyna Miliak

**Comment by kmiliak** [comment]
Please see question card on Trello my las message regarding new features.
https://trello.com/c/CSUEbxxL/7-questions

**Comment by fyahfox** [comment]
The "export account" feature is in the "More" menu on android. I think it should be the same for iOs... So whats the stand here?

**Comment by jabo38** [comment]
Fixed.  The feature is now labeled "Export Account"
