### ISSUE TITLE
When entering amounts, number keyboard should be default. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#81]
When I am sending an amount and the keyboard loads, it is always letters.  

The letter keyboard should come for messages and the number keyboard for amounts.

**Comment by kmiliak** [comment]
The number keyboard doesn't have '.' symbol, so users won't be able to put fraction amount

**Comment by fyahfox** [comment]
http://stackoverflow.com/questions/7262233/how-to-add-decimal-to-number-pad-ios

**Comment by kmiliak** [comment]
We've checked the link, and it is simple keypad but switched to numbers.
We can implement two variants:
1) Decimal Pad (but it has comma instead of point)
2) Simple keypad, but it will open numbers and symbols as default

**Comment by fyahfox** [comment]
ah ok, yes then please 2)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 13

**Comment by jabo38** [comment]
fixed

**Comment by fyahfox** [comment]
i think we had a misunderstanding here. it is of no help if the app calculates a random account and displays it as delegated account, because the app is not able to unlock delegated harvesting. this has to be done via NCC/lightwallet.

so until we have that feature (which wont happen too soon) the app should just check the network if delegated harvesting was unlocked (activated) already, and if so, display the delegated address, not priv or pub key.
